[package]
name = "tp7-client-et-serveur-simple-dns"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "dns_server"
path = "src/main.rs"

[[bin]]
name = "test_client"
path = "src/test_client.rs"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
byteorder = "1.4"
rand = "0.8"
